env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
    - go generate ./...
project_name: stripe
builds:
  - id: stripe-darwin
    ldflags:
      - -s -w -X github.com/suz-stripe/stripe-cli/pkg/version.Version={{.Version}}
    binary: stripe
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    main: ./cmd/stripe/main.go
    goos:
      - darwin
    goarch:
      - amd64
  - id: stripe-linux
    ldflags:
      - -s -w -X github.com/suz-stripe/stripe-cli/pkg/version.Version={{.Version}}
    binary: stripe
    env:
      - CGO_ENABLED=0
    main: ./cmd/stripe/main.go
    goos:
      - linux
    goarch:
      - amd64
  - id: stripe-windows
    ldflags:
      - -s -w -X github.com/suz-stripe/stripe-cli/pkg/version.Version={{.Version}}
    binary: stripe
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    main: ./cmd/stripe/main.go
    goos:
      - windows
    goarch:
      - amd64
      - 386
archives:
  -
    replacements:
      darwin: mac-os
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
    - none*
checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  -
    builds:
    - stripe-linux
    vendor: Stripe
    homepage:  https://stripe.com
    maintainer: Stripe <support@stripe.com>
    description: Stripe CLI utility
    license: Apache 2.0
    formats:
    - deb
    - rpm
    scripts:
      postinstall: "scripts/postinstall.sh"
brews:
  -
    github:
      owner: suz-stripe
      name: cli-pkg-mngr-testing
    commit_author:
      name: stripe-ci
      email: support@stripe.com
    homepage:  https://stripe.com
    description: Stripe CLI utility
    folder: brew
    install: |
      bin.install "stripe"
      rm Dir["#{bin}/{stripe-completion.bash,stripe-completion.zsh}"]
      system bin/"stripe", "completion", "--shell", "bash"
      system bin/"stripe", "completion", "--shell", "zsh"
      bash_completion.install "stripe-completion.bash"
      zsh_completion.install "stripe-completion.zsh"
      (zsh_completion/"_stripe").write <<~EOS
        #compdef stripe
        _stripe () {
          local e
          e=$(dirname ${funcsourcetrace[1]%:*})/stripe-completion.zsh
          if [[ -f $e ]]; then source $e; fi
        }
      EOS
    caveats: "❤ Thanks for installing the Stripe CLI! If this is your first time using the CLI, be sure to run `stripe login` first."
scoop:
  name: scoop/stripe
  bucket:
    owner: suz-stripe
    name: cli-pkg-mngr-testing
  commit_author:
    name: stripe-ci
    email: support@stripe.com
  homepage:  https://stripe.com
  description: Stripe CLI utility
  license: Apache 2.0
